<!DOCTYPE html>
<html>

    <head>
            <title><?= isset($title) ? $title : "My CV" ?></title>
            <meta charset="utf-8">
            <link href="/css/stylesheet.css" rel="stylesheet" type="text/css" media="all" >
            <link href="/css/timeline_responsive.css" rel="stylesheet" type="text/css"  media="all">
            <link href="/css/print.css" rel="stylesheet" type="text/css"  media="print">
            <link rel="stylesheet" href="/https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.min.js"></script>
    </head>


    <body>