<!DOCTYPE html>
<html>

    <head>
            <title><?= $title ?? "My CV" ?></title>
            <meta charset="utf-8">
            <link href="/css/stylesheet.css" rel="stylesheet" type="text/css" media="all" >
            <link href="/css/form.css" rel="stylesheet" type="text/css" media="all" >
            <link href="/css/print.css" rel="stylesheet" type="text/css"  media="print">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
            <!-- information meta tag -->
            <meta name="keywords" content="portfolio, cv, informations">
            <meta name="language" content="fr-FR" />
            <meta name="rating" content="General">
            <meta name="expires" content="never">
            <meta name="language" content="fr">
            <meta name="distribution" content="Global">
            <meta name="email" content="rousseaualexandre.lyon@gmail.com">
            <meta name="author" content="ROUSSEAU Alexandre">
            <meta name="publisher" content="ROUSSEAU Alexandre">

            <meta property="og:description" content="<?= $description ?? "My personnal informations" ?>" >
            <meta name="description" content="<?= $description ?? "My personnal informations" ?>" />
    </head>


    <body>