<?php include '_header.phtml';
/* @var $user BuildMyCV\classes\User */
?>

<div id="admin-interface" >
    <h1>Admin</h1>
    <a href="/admin">Return to admin menu </a>
    
    <!-- Flash message -->
    <?php if(isset($flash)): ?>
        <div class="flash"><?= $flash ?></div>
    <?php endif ?>
    
    <p>Bellow all items exesting in your CV, you can edit them</p>
    
    <h2>Programming langages</h2>
    
    <table><?php foreach ($user->get_programming_langages() as $lang):?>
        <tr>
            <td><?= $lang->get_name() ?></td>
            <td>
                <?php if($picture = $lang->picture_to_html()): ?>
                    <?= $picture ?>
                <?php endif ?>
            </td>
            <td>
                <form method="POST" action="/admin/items/<?= urlencode($lang->get_name()) ?>" enctype="multipart/form-data">
                    <input type="file" name="picture">
                    <input type="submit" value="send">
                </form>
            </td>
        </tr>
    <?php endforeach ?></table>
    
    <h2>Frameworks</h2>
    
    <table><?php foreach ($user->get_frameworks() as $lang):?>
        <tr>
            <td><?= $lang->get_name() ?></td>
            <td>
                <?php if($picture = $lang->picture_to_html()): ?>
                    <?= $picture ?>
                <?php endif ?>
                
            </td>
            <td>
                <form method="POST" action="/admin/items/<?= $lang->get_name() ?>" enctype="multipart/form-data">
                    <input type="file" name="picture">
                    <input type="submit" value="send">
                </form>
            </td>
        </tr>
    <?php endforeach ?></table>
    
</div>

<?php include '_footer.phtml'?>