<?php include '_header.phtml';
/* @var $user BuildMyCV\classes\User */
?>

<header>
    <h1><?= $user->complete_name() ?></h1>
    <p>Développeur passionné auto-didacte</p>
    <address><?= $user->get_address() ?></address>
    <p><?= $user->birth_informations() ?></p>
    <p><?= $user->phone_link() ?></p>
    <p><?= $user->email_link() ?></p>
</header>

<div>
    <?= $user->image() ?>
    <div id="contact"><?= $user->print_links() ?></div>
    
    
    <h2>Profil</h2>
    <p></p>
    
    <h2>Langages</h2>
    <ul></ul>
    
    <h2>Frameworks</h2>
    
    <h2>Points d'intérêt</h2>
    <ul></ul>
</div>

<section>
    <h2>Experience Professionnelle</h2>
    <ul><?php foreach($user->get_professional_experiences() as $exp ): ?>
        <?= $exp->to_html() ?>
    <?php endforeach ?></ul>
</section>

<section>
    <h2>Experience Personnelle</h2>
    <ul><?php foreach($user->get_personal_experiences() as $exp ): ?>
        <?= $exp->to_html() ?>
    <?php endforeach ?></ul>
</section>


<section>
    <h2>Diplômes & formations</h2>
    <ul> <?php foreach($user->get_trainings() as $training ): ?>
            <li><?= $training->title() ?></li>
    <?php endforeach ?></ul>
</section>

<section>
    <h2>Langues</h2>
    <?php foreach( $user->get_langages() as $langage){echo $langage->to_html(); } ?>
</section>

<?php include '_footer.phtml'?>
