<?php include '_header.phtml' ?>


<header>
    <?= $user->image() ?>
    <h1><?= $user->complete_name() ?></h1>
    <p>Développeur passionné auto-didacte</p>
</header>

<div id="contact">
    <?= $user->print_links() ?>
</div>
		


<section>
    <h2>Timeline</h2>
    <ul class="timeline">

        <?php $left = true ;
        foreach ($user->activities() as $activty): ?>
            <li <?= $left ? '' : 'class="timeline-inverted"' ?> >
                <div class="timeline-badge"><?= $activty->picture() ?></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title"><?= $activty->title() ?></h4>
                        <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> <?= $activty->date() ?></small></p>
                    </div>
                    <div class="timeline-body"> <p><?= $activty->description() ?></p></div>
                </div>
            </li>
        <?php $left = !$left ;
        endforeach ?>
    </ul>
</section>



<section>
    <h2>Compétences</h2>
    <canvas id="competencies" height="200"></canvas>
</section>



<section>
    <h2>Etudes et formations</h2>

    <h3>Etudes</h3>
    <ul>
        <?php foreach($user->diplomas as $diploma): ?>
            <li><?= $diploma->title() ?></li>
        <?php endforeach ?>
    </ul>

    <h3>Formations</h3>
    <ul>
        <?php foreach($user->trainings as $training ): ?>
            <li><?= $training->title() ?></li>
        <?php endforeach ?>
    </ul>
</section>

<section>
    <h2>Langues</h2>
    <?php foreach( $user->langages as $langage){echo $langage->to_html(); } ?>
</section>


<footer>
    <p><i class="glyphicon glyphicon-user"></i> <?= $user->birth_date->format('d/m/Y') ?> à <?= $user->town_birth ?></p>
    <p><i class="glyphicon glyphicon-home"></i> <adress><?= $user->adress ?></adress></p>
    <p><i class="glyphicon glyphicon-earphone"></i> <strong><?= $user->phone ?></strong></p>
    <p><i class="glyphicon glyphicon-envelope"></i> <a href="mailto:<?= $user->email ?>?subject=Votre%20CV"><?= $user->email ?></a></p>
    <hr/>
    <small>Icons made by <a href="http://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></small>
</footer>


<script>
    var ctx = document.getElementById("competencies").getContext('2d');
    var data = <?= $user->compentencies_to_json()?>;
    var option = { maintainAspectRatio: false };
    var myRadarChart = new Chart(ctx , {  type: 'polarArea' , data: data , options: option });
</script>

<?php include '_footer.phtml'?>