<?php include '_header.phtml';
/* @var $user BuildMyCV\classes\User */
?>
<a href="https://github.com/madeindjs/build_my_cv"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

<div id="left_panel" class="desktop">
    <?= $user->image() ?>
    
    <h1 class="mobile"><?= $user->complete_name() ?></h1>
    
    <h2>Profil</h2>
    <quote id="multiline_description"><?= $user->get_multiline_description() ?></quote>
    
    <h2>Langages</h2>
    <ul><?php foreach ($user->get_programming_langages() as $lang): ?>
        <li><?= $lang->to_html() ?></li>
    <?php endforeach ?></ul>
    
    <h2>Frameworks</h2>
    <ul><?php foreach ($user->get_frameworks() as $framework): ?>
        <li><?= $framework->to_html() ?></li>
    <?php endforeach ?></ul>
    
    <h2 class="desktop">Points d'intérêt</h2>
    <ul class="desktop"><?php foreach ($user->get_interest_points() as $pts): ?>
        <li><?= $pts ?></li>
    <?php endforeach ?></ul>
    
    <h2 class="desktop">Links</h2>
    <ul class="links"><?php foreach ($user->get_contacts_links() as $pts): ?>
        <li><?= $pts ?></li>
    <?php endforeach ?></ul>
</div>



<div id="content">
    
    <header class="desktop">
        <h1><?= $user->complete_name() ?></h1>
        <p id="oneline_description"><?= $user->get_oneline_description() ?></p>
        <address><?= $user->get_address() ?></address>
        <p><?= $user->birth_informations() ?></p>
        <p><?= $user->phone_link() ?></p>
        <p><?= $user->email_link() ?></p>
    </header>
    
    <section>
        <h2>Experience Professionnelle</h2>
        <ul class="timeline"><?php foreach($user->get_professional_experiences() as $exp ): ?>
            <li><?= $exp->to_html() ?></li>
        <?php endforeach ?></ul>
    </section>

    <section>
        <h2>Experience Personnelle</h2>
        <ul class="timeline"><?php foreach($user->get_personal_experiences() as $exp ): ?>
            <li><?= $exp->to_html() ?></li>
        <?php endforeach ?></ul>
    </section>


    <section>
        <h2>Diplômes & formations</h2>
        <ul class="timeline"><?php foreach($user->get_diplomas() as $diploma ): ?>
                <li><?= $diploma->to_html() ?></li>
        <?php endforeach ?></ul>
    </section>

</div>


<?php include '_footer.phtml'?>
